package restaurantLookup;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import FailedClasses.UtilityMethods;


public class testrss {

	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub
		Restaurant Mylocation = new Restaurant(); 
		GeoLocation myloc = new GeoLocation(33.1,-77);
		Mylocation.setLocation(myloc);
		Mylocation.setRestaurantName("My Location");
		
		
		String mypath = "src/restaurantLookup/relfiles/RESTAURANT_LIST.xls";
		UtilityMethods ul = new UtilityMethods(); 
		Restaurant[] restarr = ul.excelDataToRestaurant(ul.ReadExcel(mypath));
		DijkstraNode[] nodearr = new DijkstraNode[restarr.length];

		
		for(int i = 0; i < restarr.length; i++ ){
			nodearr[i].setName(restarr[i].getRestaurantName());
		}
		nodearr[0].addDestination(nodearr[18], (int) restarr[0].compareGeoLocation(restarr[18]));
		nodearr[0].addDestination(nodearr[37], (int) restarr[0].compareGeoLocation(restarr[37]));
		nodearr[0].addDestination(nodearr[1], (int) restarr[0].compareGeoLocation(restarr[1]));
		nodearr[2].addDestination(nodearr[1], (int) restarr[2].compareGeoLocation(restarr[1]));
		nodearr[2].addDestination(nodearr[3], (int) restarr[2].compareGeoLocation(restarr[3]));
		nodearr[2].addDestination(nodearr[4], (int) restarr[2].compareGeoLocation(restarr[4]));
		nodearr[2].addDestination(nodearr[5], (int) restarr[2].compareGeoLocation(restarr[5]));
		nodearr[2].addDestination(nodearr[21], (int) restarr[2].compareGeoLocation(restarr[21]));
		nodearr[3].addDestination(nodearr[4], (int) restarr[3].compareGeoLocation(restarr[4]));
		nodearr[3].addDestination(nodearr[5], (int) restarr[3].compareGeoLocation(restarr[5]));
		nodearr[3].addDestination(nodearr[7], (int) restarr[3].compareGeoLocation(restarr[7]));
		nodearr[3].addDestination(nodearr[8], (int) restarr[3].compareGeoLocation(restarr[8]));
		nodearr[3].addDestination(nodearr[2], (int) restarr[3].compareGeoLocation(restarr[2]));
		nodearr[4].addDestination(nodearr[5], (int) restarr[4].compareGeoLocation(restarr[5]));
		nodearr[4].addDestination(nodearr[7], (int) restarr[4].compareGeoLocation(restarr[7]));
		nodearr[4].addDestination(nodearr[32], (int) restarr[4].compareGeoLocation(restarr[32]));
		nodearr[4].addDestination(nodearr[45], (int) restarr[4].compareGeoLocation(restarr[45]));
		nodearr[4].addDestination(nodearr[2], (int) restarr[4].compareGeoLocation(restarr[2]));
		nodearr[5].addDestination(nodearr[8], (int) restarr[5].compareGeoLocation(restarr[8]));
		nodearr[5].addDestination(nodearr[32], (int) restarr[5].compareGeoLocation(restarr[32]));
		nodearr[5].addDestination(nodearr[47], (int) restarr[5].compareGeoLocation(restarr[47]));
		nodearr[5].addDestination(nodearr[22], (int) restarr[5].compareGeoLocation(restarr[22]));
		nodearr[5].addDestination(nodearr[28], (int) restarr[5].compareGeoLocation(restarr[28]));
		nodearr[5].addDestination(nodearr[23], (int) restarr[5].compareGeoLocation(restarr[23]));
		nodearr[5].addDestination(nodearr[19], (int) restarr[5].compareGeoLocation(restarr[19]));
		nodearr[5].addDestination(nodearr[33], (int) restarr[5].compareGeoLocation(restarr[33]));
		nodearr[6].addDestination(nodearr[36], (int) restarr[6].compareGeoLocation(restarr[36]));
		nodearr[6].addDestination(nodearr[9], (int) restarr[6].compareGeoLocation(restarr[9]));
		nodearr[6].addDestination(nodearr[21], (int) restarr[6].compareGeoLocation(restarr[21]));
		nodearr[6].addDestination(nodearr[44], (int) restarr[6].compareGeoLocation(restarr[44]));
		nodearr[6].addDestination(nodearr[43], (int) restarr[6].compareGeoLocation(restarr[43]));
		nodearr[6].addDestination(nodearr[9], (int) restarr[6].compareGeoLocation(restarr[9]));
		nodearr[6].addDestination(nodearr[21], (int) restarr[6].compareGeoLocation(restarr[21]));
		nodearr[6].addDestination(nodearr[7], (int) restarr[6].compareGeoLocation(restarr[7]));
		nodearr[6].addDestination(nodearr[43], (int) restarr[6].compareGeoLocation(restarr[43]));
		nodearr[7].addDestination(nodearr[21], (int) restarr[7].compareGeoLocation(restarr[21]));
		nodearr[7].addDestination(nodearr[43], (int) restarr[7].compareGeoLocation(restarr[43]));
		nodearr[7].addDestination(nodearr[17], (int) restarr[7].compareGeoLocation(restarr[17]));
		nodearr[7].addDestination(nodearr[31], (int) restarr[7].compareGeoLocation(restarr[31]));
		nodearr[7].addDestination(nodearr[42], (int) restarr[7].compareGeoLocation(restarr[42]));
		nodearr[8].addDestination(nodearr[17], (int) restarr[8].compareGeoLocation(restarr[17]));
		nodearr[8].addDestination(nodearr[19], (int) restarr[8].compareGeoLocation(restarr[19]));
		nodearr[8].addDestination(nodearr[22], (int) restarr[8].compareGeoLocation(restarr[22]));
		nodearr[8].addDestination(nodearr[28], (int) restarr[8].compareGeoLocation(restarr[28]));
		nodearr[8].addDestination(nodearr[23], (int) restarr[8].compareGeoLocation(restarr[23]));
		nodearr[8].addDestination(nodearr[33], (int) restarr[8].compareGeoLocation(restarr[33]));
		nodearr[8].addDestination(nodearr[10], (int) restarr[8].compareGeoLocation(restarr[10]));
		nodearr[9].addDestination(nodearr[20], (int) restarr[9].compareGeoLocation(restarr[20]));
		nodearr[9].addDestination(nodearr[41], (int) restarr[9].compareGeoLocation(restarr[41]));
		nodearr[9].addDestination(nodearr[42], (int) restarr[9].compareGeoLocation(restarr[42]));
		nodearr[9].addDestination(nodearr[43], (int) restarr[9].compareGeoLocation(restarr[43]));
		nodearr[9].addDestination(nodearr[44], (int) restarr[9].compareGeoLocation(restarr[44]));
		nodearr[9].addDestination(nodearr[46], (int) restarr[9].compareGeoLocation(restarr[46]));
		nodearr[9].addDestination(nodearr[7], (int) restarr[9].compareGeoLocation(restarr[7]));
		nodearr[10].addDestination(nodearr[11], (int) restarr[10].compareGeoLocation(restarr[11]));
		nodearr[10].addDestination(nodearr[12], (int) restarr[10].compareGeoLocation(restarr[12]));
		nodearr[10].addDestination(nodearr[51], (int) restarr[10].compareGeoLocation(restarr[51]));
		nodearr[10].addDestination(nodearr[52], (int) restarr[10].compareGeoLocation(restarr[52]));
		nodearr[11].addDestination(nodearr[12], (int) restarr[11].compareGeoLocation(restarr[12]));
		nodearr[11].addDestination(nodearr[24], (int) restarr[11].compareGeoLocation(restarr[24]));
		nodearr[12].addDestination(nodearr[4], (int) restarr[12].compareGeoLocation(restarr[4]));
		nodearr[12].addDestination(nodearr[53], (int) restarr[12].compareGeoLocation(restarr[53]));
		nodearr[13].addDestination(nodearr[14], (int) restarr[13].compareGeoLocation(restarr[14]));
		nodearr[13].addDestination(nodearr[12], (int) restarr[13].compareGeoLocation(restarr[12]));
		nodearr[13].addDestination(nodearr[25], (int) restarr[13].compareGeoLocation(restarr[25]));
		nodearr[13].addDestination(nodearr[29], (int) restarr[13].compareGeoLocation(restarr[29]));
		nodearr[13].addDestination(nodearr[30], (int) restarr[13].compareGeoLocation(restarr[30]));
		nodearr[13].addDestination(nodearr[41], (int) restarr[13].compareGeoLocation(restarr[41]));
		nodearr[14].addDestination(nodearr[16], (int) restarr[14].compareGeoLocation(restarr[16]));
		nodearr[14].addDestination(nodearr[35], (int) restarr[14].compareGeoLocation(restarr[35]));
		nodearr[14].addDestination(nodearr[25], (int) restarr[14].compareGeoLocation(restarr[25]));
		nodearr[14].addDestination(nodearr[29], (int) restarr[14].compareGeoLocation(restarr[29]));
		nodearr[15].addDestination(nodearr[20], (int) restarr[15].compareGeoLocation(restarr[20]));
		nodearr[15].addDestination(nodearr[41], (int) restarr[15].compareGeoLocation(restarr[41]));
		nodearr[15].addDestination(nodearr[42], (int) restarr[15].compareGeoLocation(restarr[42]));
		nodearr[15].addDestination(nodearr[43], (int) restarr[15].compareGeoLocation(restarr[43]));
		nodearr[15].addDestination(nodearr[44], (int) restarr[15].compareGeoLocation(restarr[44]));
		nodearr[15].addDestination(nodearr[46], (int) restarr[15].compareGeoLocation(restarr[46]));
		nodearr[15].addDestination(nodearr[9], (int) restarr[15].compareGeoLocation(restarr[9]));
		nodearr[15].addDestination(nodearr[57], (int) restarr[15].compareGeoLocation(restarr[57]));
		nodearr[15].addDestination(nodearr[58], (int) restarr[15].compareGeoLocation(restarr[58]));
		nodearr[16].addDestination(nodearr[20], (int) restarr[16].compareGeoLocation(restarr[20]));
		nodearr[16].addDestination(nodearr[30], (int) restarr[16].compareGeoLocation(restarr[30]));
		nodearr[16].addDestination(nodearr[37], (int) restarr[16].compareGeoLocation(restarr[37]));
		nodearr[16].addDestination(nodearr[47], (int) restarr[16].compareGeoLocation(restarr[47]));
		nodearr[17].addDestination(nodearr[47], (int) restarr[17].compareGeoLocation(restarr[47]));
		nodearr[17].addDestination(nodearr[22], (int) restarr[17].compareGeoLocation(restarr[22]));
		nodearr[17].addDestination(nodearr[28], (int) restarr[17].compareGeoLocation(restarr[28]));
		nodearr[17].addDestination(nodearr[23], (int) restarr[17].compareGeoLocation(restarr[23]));
		nodearr[17].addDestination(nodearr[19], (int) restarr[17].compareGeoLocation(restarr[19]));
		nodearr[18].addDestination(nodearr[30], (int) restarr[18].compareGeoLocation(restarr[30]));
		nodearr[18].addDestination(nodearr[32], (int) restarr[18].compareGeoLocation(restarr[32]));
		nodearr[18].addDestination(nodearr[38], (int) restarr[18].compareGeoLocation(restarr[38]));
		nodearr[18].addDestination(nodearr[27], (int) restarr[18].compareGeoLocation(restarr[27]));
		nodearr[18].addDestination(nodearr[31], (int) restarr[18].compareGeoLocation(restarr[31]));
		nodearr[19].addDestination(nodearr[57], (int) restarr[19].compareGeoLocation(restarr[57]));
		nodearr[19].addDestination(nodearr[22], (int) restarr[19].compareGeoLocation(restarr[22]));
		nodearr[19].addDestination(nodearr[28], (int) restarr[19].compareGeoLocation(restarr[28]));
		nodearr[19].addDestination(nodearr[23], (int) restarr[19].compareGeoLocation(restarr[23]));
		nodearr[19].addDestination(nodearr[33], (int) restarr[19].compareGeoLocation(restarr[33]));
		nodearr[20].addDestination(nodearr[1], (int) restarr[20].compareGeoLocation(restarr[1]));
		nodearr[20].addDestination(nodearr[41], (int) restarr[20].compareGeoLocation(restarr[41]));
		nodearr[20].addDestination(nodearr[42], (int) restarr[20].compareGeoLocation(restarr[42]));
		nodearr[20].addDestination(nodearr[43], (int) restarr[20].compareGeoLocation(restarr[43]));
		nodearr[20].addDestination(nodearr[44], (int) restarr[20].compareGeoLocation(restarr[44]));
		nodearr[20].addDestination(nodearr[46], (int) restarr[20].compareGeoLocation(restarr[46]));
		nodearr[20].addDestination(nodearr[29], (int) restarr[20].compareGeoLocation(restarr[29]));
		nodearr[21].addDestination(nodearr[2], (int) restarr[21].compareGeoLocation(restarr[2]));
		nodearr[21].addDestination(nodearr[9], (int) restarr[21].compareGeoLocation(restarr[9]));
		nodearr[21].addDestination(nodearr[35], (int) restarr[21].compareGeoLocation(restarr[35]));
		nodearr[21].addDestination(nodearr[31], (int) restarr[21].compareGeoLocation(restarr[31]));
		nodearr[21].addDestination(nodearr[16], (int) restarr[21].compareGeoLocation(restarr[16]));
		nodearr[21].addDestination(nodearr[26], (int) restarr[21].compareGeoLocation(restarr[26]));
		nodearr[21].addDestination(nodearr[45], (int) restarr[21].compareGeoLocation(restarr[45]));
		nodearr[21].addDestination(nodearr[0], (int) restarr[21].compareGeoLocation(restarr[0]));
		nodearr[21].addDestination(nodearr[40], (int) restarr[21].compareGeoLocation(restarr[40]));
		nodearr[22].addDestination(nodearr[51], (int) restarr[22].compareGeoLocation(restarr[51]));
		nodearr[22].addDestination(nodearr[28], (int) restarr[22].compareGeoLocation(restarr[28]));
		nodearr[22].addDestination(nodearr[23], (int) restarr[22].compareGeoLocation(restarr[23]));
		nodearr[22].addDestination(nodearr[33], (int) restarr[22].compareGeoLocation(restarr[33]));
		nodearr[23].addDestination(nodearr[11], (int) restarr[23].compareGeoLocation(restarr[11]));
		nodearr[23].addDestination(nodearr[33], (int) restarr[23].compareGeoLocation(restarr[33]));
		nodearr[23].addDestination(nodearr[14], (int) restarr[23].compareGeoLocation(restarr[14]));
		nodearr[23].addDestination(nodearr[37], (int) restarr[23].compareGeoLocation(restarr[37]));
		nodearr[24].addDestination(nodearr[14], (int) restarr[24].compareGeoLocation(restarr[14]));
		nodearr[24].addDestination(nodearr[13], (int) restarr[24].compareGeoLocation(restarr[13]));
		nodearr[24].addDestination(nodearr[25], (int) restarr[24].compareGeoLocation(restarr[25]));
		nodearr[24].addDestination(nodearr[29], (int) restarr[24].compareGeoLocation(restarr[29]));
		nodearr[24].addDestination(nodearr[6], (int) restarr[24].compareGeoLocation(restarr[6]));
		nodearr[25].addDestination(nodearr[53], (int) restarr[25].compareGeoLocation(restarr[53]));
		nodearr[25].addDestination(nodearr[11], (int) restarr[25].compareGeoLocation(restarr[11]));
		nodearr[25].addDestination(nodearr[6], (int) restarr[25].compareGeoLocation(restarr[6]));
		nodearr[25].addDestination(nodearr[29], (int) restarr[25].compareGeoLocation(restarr[29]));
		nodearr[26].addDestination(nodearr[27], (int) restarr[26].compareGeoLocation(restarr[27]));
		nodearr[26].addDestination(nodearr[7], (int) restarr[26].compareGeoLocation(restarr[7]));
		nodearr[26].addDestination(nodearr[1], (int) restarr[26].compareGeoLocation(restarr[1]));
		nodearr[26].addDestination(nodearr[37], (int) restarr[26].compareGeoLocation(restarr[37]));
		nodearr[27].addDestination(nodearr[9], (int) restarr[27].compareGeoLocation(restarr[9]));
		nodearr[27].addDestination(nodearr[52], (int) restarr[27].compareGeoLocation(restarr[52]));
		nodearr[27].addDestination(nodearr[42], (int) restarr[27].compareGeoLocation(restarr[42]));
		nodearr[27].addDestination(nodearr[6], (int) restarr[27].compareGeoLocation(restarr[6]));
		nodearr[28].addDestination(nodearr[50], (int) restarr[28].compareGeoLocation(restarr[50]));
		nodearr[28].addDestination(nodearr[23], (int) restarr[28].compareGeoLocation(restarr[23]));
		nodearr[28].addDestination(nodearr[33], (int) restarr[28].compareGeoLocation(restarr[33]));
		nodearr[29].addDestination(nodearr[47], (int) restarr[29].compareGeoLocation(restarr[47]));
		nodearr[29].addDestination(nodearr[52], (int) restarr[29].compareGeoLocation(restarr[52]));
		nodearr[29].addDestination(nodearr[51], (int) restarr[29].compareGeoLocation(restarr[51]));
		nodearr[29].addDestination(nodearr[54], (int) restarr[29].compareGeoLocation(restarr[54]));
		nodearr[30].addDestination(nodearr[57], (int) restarr[30].compareGeoLocation(restarr[57]));
		nodearr[30].addDestination(nodearr[32], (int) restarr[30].compareGeoLocation(restarr[32]));
		nodearr[30].addDestination(nodearr[38], (int) restarr[30].compareGeoLocation(restarr[38]));
		nodearr[30].addDestination(nodearr[6], (int) restarr[30].compareGeoLocation(restarr[6]));
		nodearr[31].addDestination(nodearr[21], (int) restarr[31].compareGeoLocation(restarr[21]));
		nodearr[31].addDestination(nodearr[49], (int) restarr[31].compareGeoLocation(restarr[49]));
		nodearr[31].addDestination(nodearr[56], (int) restarr[31].compareGeoLocation(restarr[56]));
		nodearr[31].addDestination(nodearr[33], (int) restarr[31].compareGeoLocation(restarr[33]));
		nodearr[31].addDestination(nodearr[1], (int) restarr[31].compareGeoLocation(restarr[1]));
		nodearr[32].addDestination(nodearr[57], (int) restarr[32].compareGeoLocation(restarr[57]));
		nodearr[32].addDestination(nodearr[53], (int) restarr[32].compareGeoLocation(restarr[53]));
		nodearr[32].addDestination(nodearr[33], (int) restarr[32].compareGeoLocation(restarr[33]));
		nodearr[32].addDestination(nodearr[40], (int) restarr[32].compareGeoLocation(restarr[40]));
		nodearr[33].addDestination(nodearr[52], (int) restarr[33].compareGeoLocation(restarr[52]));
		nodearr[33].addDestination(nodearr[51], (int) restarr[33].compareGeoLocation(restarr[51]));
		nodearr[34].addDestination(nodearr[57], (int) restarr[34].compareGeoLocation(restarr[57]));
		nodearr[34].addDestination(nodearr[32], (int) restarr[34].compareGeoLocation(restarr[32]));
		nodearr[34].addDestination(nodearr[38], (int) restarr[34].compareGeoLocation(restarr[38]));
		nodearr[34].addDestination(nodearr[44], (int) restarr[34].compareGeoLocation(restarr[44]));
		nodearr[35].addDestination(nodearr[2], (int) restarr[35].compareGeoLocation(restarr[2]));
		nodearr[35].addDestination(nodearr[3], (int) restarr[35].compareGeoLocation(restarr[3]));
		nodearr[35].addDestination(nodearr[4], (int) restarr[35].compareGeoLocation(restarr[4]));
		nodearr[35].addDestination(nodearr[6], (int) restarr[35].compareGeoLocation(restarr[6]));
		nodearr[35].addDestination(nodearr[7], (int) restarr[35].compareGeoLocation(restarr[7]));
		nodearr[36].addDestination(nodearr[4], (int) restarr[36].compareGeoLocation(restarr[4]));
		nodearr[36].addDestination(nodearr[30], (int) restarr[36].compareGeoLocation(restarr[30]));
		nodearr[36].addDestination(nodearr[41], (int) restarr[36].compareGeoLocation(restarr[41]));
		nodearr[36].addDestination(nodearr[37], (int) restarr[36].compareGeoLocation(restarr[37]));
		nodearr[37].addDestination(nodearr[20], (int) restarr[37].compareGeoLocation(restarr[20]));
		nodearr[37].addDestination(nodearr[30], (int) restarr[37].compareGeoLocation(restarr[30]));
		nodearr[37].addDestination(nodearr[40], (int) restarr[37].compareGeoLocation(restarr[40]));
		nodearr[38].addDestination(nodearr[25], (int) restarr[38].compareGeoLocation(restarr[25]));
		nodearr[38].addDestination(nodearr[1], (int) restarr[38].compareGeoLocation(restarr[1]));
		nodearr[38].addDestination(nodearr[36], (int) restarr[38].compareGeoLocation(restarr[36]));
		nodearr[38].addDestination(nodearr[40], (int) restarr[38].compareGeoLocation(restarr[40]));
		nodearr[39].addDestination(nodearr[40], (int) restarr[39].compareGeoLocation(restarr[40]));
		nodearr[39].addDestination(nodearr[45], (int) restarr[39].compareGeoLocation(restarr[45]));
		nodearr[39].addDestination(nodearr[47], (int) restarr[39].compareGeoLocation(restarr[47]));
		nodearr[39].addDestination(nodearr[36], (int) restarr[39].compareGeoLocation(restarr[36]));
		nodearr[39].addDestination(nodearr[48], (int) restarr[39].compareGeoLocation(restarr[48]));
		nodearr[39].addDestination(nodearr[30], (int) restarr[39].compareGeoLocation(restarr[30]));
		nodearr[39].addDestination(nodearr[46], (int) restarr[39].compareGeoLocation(restarr[46]));
		nodearr[39].addDestination(nodearr[4], (int) restarr[39].compareGeoLocation(restarr[4]));
		nodearr[40].addDestination(nodearr[0], (int) restarr[40].compareGeoLocation(restarr[0]));
		nodearr[40].addDestination(nodearr[51], (int) restarr[40].compareGeoLocation(restarr[51]));
		nodearr[40].addDestination(nodearr[48], (int) restarr[40].compareGeoLocation(restarr[48]));
		nodearr[41].addDestination(nodearr[32], (int) restarr[41].compareGeoLocation(restarr[32]));
		nodearr[41].addDestination(nodearr[26], (int) restarr[41].compareGeoLocation(restarr[26]));
		nodearr[41].addDestination(nodearr[42], (int) restarr[41].compareGeoLocation(restarr[42]));
		nodearr[41].addDestination(nodearr[43], (int) restarr[41].compareGeoLocation(restarr[43]));
		nodearr[41].addDestination(nodearr[44], (int) restarr[41].compareGeoLocation(restarr[44]));
		nodearr[41].addDestination(nodearr[46], (int) restarr[41].compareGeoLocation(restarr[46]));
		nodearr[41].addDestination(nodearr[51], (int) restarr[41].compareGeoLocation(restarr[51]));
		nodearr[42].addDestination(nodearr[24], (int) restarr[42].compareGeoLocation(restarr[24]));
		nodearr[42].addDestination(nodearr[52], (int) restarr[42].compareGeoLocation(restarr[52]));
		nodearr[42].addDestination(nodearr[43], (int) restarr[42].compareGeoLocation(restarr[43]));
		nodearr[42].addDestination(nodearr[44], (int) restarr[42].compareGeoLocation(restarr[44]));
		nodearr[42].addDestination(nodearr[46], (int) restarr[42].compareGeoLocation(restarr[46]));
		nodearr[43].addDestination(nodearr[55], (int) restarr[43].compareGeoLocation(restarr[55]));
		nodearr[43].addDestination(nodearr[44], (int) restarr[43].compareGeoLocation(restarr[44]));
		nodearr[43].addDestination(nodearr[46], (int) restarr[43].compareGeoLocation(restarr[46]));
		nodearr[44].addDestination(nodearr[12], (int) restarr[44].compareGeoLocation(restarr[12]));
		nodearr[44].addDestination(nodearr[24], (int) restarr[44].compareGeoLocation(restarr[24]));
		nodearr[45].addDestination(nodearr[47], (int) restarr[45].compareGeoLocation(restarr[47]));
		nodearr[45].addDestination(nodearr[31], (int) restarr[45].compareGeoLocation(restarr[31]));
		nodearr[46].addDestination(nodearr[35], (int) restarr[46].compareGeoLocation(restarr[35]));
		nodearr[46].addDestination(nodearr[36], (int) restarr[46].compareGeoLocation(restarr[36]));
		nodearr[47].addDestination(nodearr[51], (int) restarr[47].compareGeoLocation(restarr[51]));
		nodearr[48].addDestination(nodearr[10], (int) restarr[48].compareGeoLocation(restarr[10]));
		nodearr[48].addDestination(nodearr[20], (int) restarr[48].compareGeoLocation(restarr[20]));
		nodearr[48].addDestination(nodearr[30], (int) restarr[48].compareGeoLocation(restarr[30]));
		nodearr[48].addDestination(nodearr[35], (int) restarr[48].compareGeoLocation(restarr[35]));
		nodearr[49].addDestination(nodearr[50], (int) restarr[49].compareGeoLocation(restarr[50]));
		nodearr[49].addDestination(nodearr[51], (int) restarr[49].compareGeoLocation(restarr[51]));
		nodearr[49].addDestination(nodearr[53], (int) restarr[49].compareGeoLocation(restarr[53]));
		nodearr[49].addDestination(nodearr[27], (int) restarr[49].compareGeoLocation(restarr[27]));
		nodearr[50].addDestination(nodearr[51], (int) restarr[50].compareGeoLocation(restarr[51]));
		nodearr[50].addDestination(nodearr[53], (int) restarr[50].compareGeoLocation(restarr[53]));
		nodearr[50].addDestination(nodearr[1], (int) restarr[50].compareGeoLocation(restarr[1]));
		nodearr[51].addDestination(nodearr[53], (int) restarr[51].compareGeoLocation(restarr[53]));
		nodearr[51].addDestination(nodearr[6], (int) restarr[51].compareGeoLocation(restarr[6]));
		nodearr[51].addDestination(nodearr[18], (int) restarr[51].compareGeoLocation(restarr[18]));
		nodearr[52].addDestination(nodearr[56], (int) restarr[52].compareGeoLocation(restarr[56]));
		nodearr[53].addDestination(nodearr[6], (int) restarr[53].compareGeoLocation(restarr[6]));
		nodearr[54].addDestination(nodearr[7], (int) restarr[54].compareGeoLocation(restarr[7]));
		nodearr[54].addDestination(nodearr[24], (int) restarr[54].compareGeoLocation(restarr[24]));
		nodearr[54].addDestination(nodearr[55], (int) restarr[54].compareGeoLocation(restarr[55]));
		nodearr[55].addDestination(nodearr[42], (int) restarr[55].compareGeoLocation(restarr[42]));
		nodearr[55].addDestination(nodearr[43], (int) restarr[55].compareGeoLocation(restarr[43]));
		nodearr[55].addDestination(nodearr[44], (int) restarr[55].compareGeoLocation(restarr[44]));
		nodearr[55].addDestination(nodearr[46], (int) restarr[55].compareGeoLocation(restarr[46]));
		nodearr[56].addDestination(nodearr[58], (int) restarr[56].compareGeoLocation(restarr[58]));
		nodearr[56].addDestination(nodearr[49], (int) restarr[56].compareGeoLocation(restarr[49]));
		nodearr[56].addDestination(nodearr[55], (int) restarr[56].compareGeoLocation(restarr[55]));
		nodearr[57].addDestination(nodearr[58], (int) restarr[57].compareGeoLocation(restarr[58]));
		nodearr[57].addDestination(nodearr[49], (int) restarr[57].compareGeoLocation(restarr[49]));
		nodearr[57].addDestination(nodearr[55], (int) restarr[57].compareGeoLocation(restarr[55]));
		nodearr[57].addDestination(nodearr[52], (int) restarr[57].compareGeoLocation(restarr[52]));
		nodearr[58].addDestination(nodearr[41], (int) restarr[58].compareGeoLocation(restarr[41]));
		nodearr[58].addDestination(nodearr[42], (int) restarr[58].compareGeoLocation(restarr[42]));
		nodearr[58].addDestination(nodearr[43], (int) restarr[58].compareGeoLocation(restarr[43]));

		DijkstraGraph graph = new DijkstraGraph(); 
		for(int i = 0; i < nodearr.length; i++ ){
			graph.addNode(nodearr[i]);
		}
		graph = DijkstraShortestDistance.calculateShortestPathFromSource(graph, nodearr[0]);
		
		List<DijkstraNode> sohrtestPathForNodeB = Arrays.asList(nodearr[0]);

		
		
	}

}
